// <auto-generated />
using System;
using Conference.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Conference.Migrations
{
    [DbContext(typeof(EntityFrameworkContext))]
    partial class EntityFrameworkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Conference.Domain.Decision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Meeting_Decisions")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Meeting_Decisions");

                    b.ToTable("Decisions");
                });

            modelBuilder.Entity("Conference.Domain.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Meeting_Documents")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Meeting_Documents");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Conference.Domain.Meeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("VotingTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("Conference.Domain.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MeetingId")
                        .HasColumnType("int");

                    b.Property<int?>("Option_Members")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.HasIndex("Option_Members");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Conference.Domain.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Meeting_Notes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Meeting_Notes");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Conference.Domain.Option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Meeting_Votes")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Meeting_Votes");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("Conference.Domain.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Meeting_Agenda")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Meeting_Agenda");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Conference.Domain.Decision", b =>
                {
                    b.HasOne("Conference.Domain.Meeting", null)
                        .WithMany("Decisions")
                        .HasForeignKey("Meeting_Decisions");
                });

            modelBuilder.Entity("Conference.Domain.Document", b =>
                {
                    b.HasOne("Conference.Domain.Meeting", null)
                        .WithMany("Documents")
                        .HasForeignKey("Meeting_Documents");
                });

            modelBuilder.Entity("Conference.Domain.Member", b =>
                {
                    b.HasOne("Conference.Domain.Meeting", null)
                        .WithMany("Members")
                        .HasForeignKey("MeetingId");

                    b.HasOne("Conference.Domain.Option", null)
                        .WithMany("Members")
                        .HasForeignKey("Option_Members");
                });

            modelBuilder.Entity("Conference.Domain.Note", b =>
                {
                    b.HasOne("Conference.Domain.Meeting", null)
                        .WithMany("Notes")
                        .HasForeignKey("Meeting_Notes");
                });

            modelBuilder.Entity("Conference.Domain.Option", b =>
                {
                    b.HasOne("Conference.Domain.Meeting", null)
                        .WithMany("Votes")
                        .HasForeignKey("Meeting_Votes");
                });

            modelBuilder.Entity("Conference.Domain.Question", b =>
                {
                    b.HasOne("Conference.Domain.Meeting", null)
                        .WithMany("Agenda")
                        .HasForeignKey("Meeting_Agenda");
                });

            modelBuilder.Entity("Conference.Domain.Meeting", b =>
                {
                    b.Navigation("Agenda");

                    b.Navigation("Decisions");

                    b.Navigation("Documents");

                    b.Navigation("Members");

                    b.Navigation("Notes");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Conference.Domain.Option", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
